module.exports = {
  categories: [
    {
      id: 'number',
      title: '数字',
      items: [
        {
          word: 'one',
          phonetic: '/wʌn/',
          meaning: '一',
          sentence: "It's one.",
          image: 'english-number-one',
          audio: '/subpkg/english-number/static/audio/one.mp3',
          sentenceAudio: '/subpkg/english-number/static/audio/one-sentence.mp3',
        },
        {
          word: 'two',
          phonetic: '/tuː/',
          meaning: '二',
          sentence: "It's two.",
          image: 'english-number-two',
          audio: '/subpkg/english-number/static/audio/two.mp3',
          sentenceAudio: '/subpkg/english-number/static/audio/two-sentence.mp3',
        },
        {
          word: 'three',
          phonetic: '/θriː/',
          meaning: '三',
          sentence: "It's three.",
          image: 'english-number-three',
          audio: '/subpkg/english-number/static/audio/three.mp3',
          sentenceAudio: '/subpkg/english-number/static/audio/three-sentence.mp3',
        },
        {
          word: 'four',
          phonetic: '/fɔr/',
          meaning: '四',
          sentence: "It's four.",
          image: 'english-number-four',
          audio: '/subpkg/english-number/static/audio/four.mp3',
          sentenceAudio: '/subpkg/english-number/static/audio/four-sentence.mp3',
        },
        {
          word: 'five',
          phonetic: '/faɪv/',
          meaning: '五',
          sentence: "It's five.",
          image: 'english-number-five',
          audio: '/subpkg/english-number/static/audio/five.mp3',
          sentenceAudio: '/subpkg/english-number/static/audio/five-sentence.mp3',
        },
        {
          word: 'six',
          phonetic: '/sɪks/',
          meaning: '六',
          sentence: "It's six.",
          image: 'english-number-six',
          audio: '/subpkg/english-number/static/audio/six.mp3',
          sentenceAudio: '/subpkg/english-number/static/audio/six-sentence.mp3',
        },
        {
          word: 'seven',
          phonetic: '/ˈsevən/',
          meaning: '七',
          sentence: "It's seven.",
          image: 'english-number-seven',
          audio: '/subpkg/english-number/static/audio/seven.mp3',
          sentenceAudio: '/subpkg/english-number/static/audio/seven-sentence.mp3',
        },
        {
          word: 'eight',
          phonetic: '/eɪt/',
          meaning: '八',
          sentence: "It's eight.",
          image: 'english-number-eight',
          audio: '/subpkg/english-number/static/audio/eight.mp3',
          sentenceAudio: '/subpkg/english-number/static/audio/eight-sentence.mp3',
        },
        {
          word: 'nine',
          phonetic: '/naɪn/',
          meaning: '九',
          sentence: "It's nine.",
          image: 'english-number-nine',
          audio: '/subpkg/english-number/static/audio/nine.mp3',
          sentenceAudio: '/subpkg/english-number/static/audio/nine-sentence.mp3',
        },
        {
          word: 'ten',
          phonetic: '/ten/',
          meaning: '十',
          sentence: "It's ten.",
          image: 'english-number-ten',
          audio: '/subpkg/english-number/static/audio/ten.mp3',
          sentenceAudio: '/subpkg/english-number/static/audio/ten-sentence.mp3',
        },
        {
          word: 'hundred',
          phonetic: '/ˈhʌndrəd/',
          meaning: '一百',
          sentence: "It's a hundred.",
          image: 'english-number-hundred',
          audio: '/subpkg/english-number/static/audio/hundred.mp3',
          sentenceAudio: '/subpkg/english-number/static/audio/hundred-sentence.mp3',
        },
        {
          word: 'thousand',
          phonetic: '/ˈθaʊznd/',
          meaning: '一千',
          sentence: "It's a thousand.",
          image: 'english-number-thousand',
          audio: '/subpkg/english-number/static/audio/thousand.mp3',
          sentenceAudio: '/subpkg/english-number/static/audio/thousand-sentence.mp3',
        },
      ],
    },
    {
      id: 'color',
      title: '颜色',
      items: [
        {
          word: 'black',
          phonetic: '/blæk/',
          meaning: '黑色',
          sentence: "It's black.",
          image: 'english-color-black',
          audio: '/subpkg/english-color/static/audio/black.mp3',
          sentenceAudio: '/subpkg/english-color/static/audio/black-sentence.mp3',
        },
        {
          word: 'blue',
          phonetic: '/bluː/',
          meaning: '蓝色',
          sentence: "It's blue.",
          image: 'english-color-blue',
          audio: '/subpkg/english-color/static/audio/blue.mp3',
          sentenceAudio: '/subpkg/english-color/static/audio/blue-sentence.mp3',
        },
        {
          word: 'brown',
          phonetic: '/braʊn/',
          meaning: '棕色',
          sentence: "It's brown.",
          image: 'english-color-brown',
          audio: '/subpkg/english-color/static/audio/brown.mp3',
          sentenceAudio: '/subpkg/english-color/static/audio/brown-sentence.mp3',
        },
        {
          word: 'gold',
          phonetic: '/ɡoʊld/',
          meaning: '金色',
          sentence: "It's gold.",
          image: 'english-color-gold',
          audio: '/subpkg/english-color/static/audio/gold.mp3',
          sentenceAudio: '/subpkg/english-color/static/audio/gold-sentence.mp3',
        },
        {
          word: 'gray',
          phonetic: '/ɡreɪ/',
          meaning: '灰色',
          sentence: "It's gray.",
          image: 'english-color-gray',
          audio: '/subpkg/english-color/static/audio/gray.mp3',
          sentenceAudio: '/subpkg/english-color/static/audio/gray-sentence.mp3',
        },
        {
          word: 'green',
          phonetic: '/ɡriːn/',
          meaning: '绿色',
          sentence: "It's green.",
          image: 'english-color-green',
          audio: '/subpkg/english-color/static/audio/green.mp3',
          sentenceAudio: '/subpkg/english-color/static/audio/green-sentence.mp3',
        },
        {
          word: 'orange',
          phonetic: '/ˈɔrɪndʒ/',
          meaning: '橙色',
          sentence: "It's orange.",
          image: 'english-color-orange',
          audio: '/subpkg/english-color/static/audio/orange-color.mp3',
          sentenceAudio: '/subpkg/english-color/static/audio/orange-color-sentence.mp3',
          audioKey: 'orange-color',
        },
        {
          word: 'pink',
          phonetic: '/pɪŋk/',
          meaning: '粉色',
          sentence: "It's pink.",
          image: 'english-color-pink',
          audio: '/subpkg/english-color/static/audio/pink.mp3',
          sentenceAudio: '/subpkg/english-color/static/audio/pink-sentence.mp3',
        },
        {
          word: 'purple',
          phonetic: '/ˈpɜrpl/',
          meaning: '紫色',
          sentence: "It's purple.",
          image: 'english-color-purple',
          audio: '/subpkg/english-color/static/audio/purple.mp3',
          sentenceAudio: '/subpkg/english-color/static/audio/purple-sentence.mp3',
        },
        {
          word: 'red',
          phonetic: '/red/',
          meaning: '红色',
          sentence: "It's red.",
          image: 'english-color-red',
          audio: '/subpkg/english-color/static/audio/red.mp3',
          sentenceAudio: '/subpkg/english-color/static/audio/red-sentence.mp3',
        },
        {
          word: 'white',
          phonetic: '/waɪt/',
          meaning: '白色',
          sentence: "It's white.",
          image: 'english-color-white',
          audio: '/subpkg/english-color/static/audio/white.mp3',
          sentenceAudio: '/subpkg/english-color/static/audio/white-sentence.mp3',
        },
        {
          word: 'yellow',
          phonetic: '/ˈjeloʊ/',
          meaning: '黄色',
          sentence: "It's yellow.",
          image: 'english-color-yellow',
          audio: '/subpkg/english-color/static/audio/yellow.mp3',
          sentenceAudio: '/subpkg/english-color/static/audio/yellow-sentence.mp3',
        },
      ],
    },
    {
      id: 'animal',
      title: '动物',
      items: [
        {
          word: 'bear',
          phonetic: '/ber/',
          meaning: '熊',
          sentence: 'A bear.',
          image: 'english-animal-bear',
          audio: '/subpkg/english-animal/static/audio/bear.mp3',
          sentenceAudio: '/subpkg/english-animal/static/audio/bear-sentence.mp3',
        },
        {
          word: 'bird',
          phonetic: '/bɜrd/',
          meaning: '鸟',
          sentence: 'A bird.',
          image: 'english-animal-bird',
          audio: '/subpkg/english-animal/static/audio/bird.mp3',
          sentenceAudio: '/subpkg/english-animal/static/audio/bird-sentence.mp3',
        },
        {
          word: 'cat',
          phonetic: '/kæt/',
          meaning: '猫',
          sentence: 'A cat.',
          image: 'english-animal-cat',
          audio: '/subpkg/english-animal/static/audio/cat.mp3',
          sentenceAudio: '/subpkg/english-animal/static/audio/cat-sentence.mp3',
        },
        {
          word: 'dog',
          phonetic: '/dɑɡ/',
          meaning: '狗',
          sentence: 'A dog.',
          image: 'english-animal-dog',
          audio: '/subpkg/english-animal/static/audio/dog.mp3',
          sentenceAudio: '/subpkg/english-animal/static/audio/dog-sentence.mp3',
        },
        {
          word: 'duck',
          phonetic: '/dʌk/',
          meaning: '鸭子',
          sentence: 'A duck.',
          image: 'english-animal-duck',
          audio: '/subpkg/english-animal/static/audio/duck.mp3',
          sentenceAudio: '/subpkg/english-animal/static/audio/duck-sentence.mp3',
        },
        {
          word: 'fish',
          phonetic: '/fɪʃ/',
          meaning: '鱼',
          sentence: 'A fish.',
          image: 'english-animal-fish',
          audio: '/subpkg/english-animal/static/audio/fish.mp3',
          sentenceAudio: '/subpkg/english-animal/static/audio/fish-sentence.mp3',
        },
        {
          word: 'lion',
          phonetic: '/ˈlaɪən/',
          meaning: '狮子',
          sentence: 'A lion.',
          image: 'english-animal-lion',
          audio: '/subpkg/english-animal/static/audio/lion.mp3',
          sentenceAudio: '/subpkg/english-animal/static/audio/lion-sentence.mp3',
        },
        {
          word: 'monkey',
          phonetic: '/ˈmʌŋki/',
          meaning: '猴子',
          sentence: 'A monkey.',
          image: 'english-animal-monkey',
          audio: '/subpkg/english-animal/static/audio/monkey.mp3',
          sentenceAudio: '/subpkg/english-animal/static/audio/monkey-sentence.mp3',
        },
        {
          word: 'panda',
          phonetic: '/ˈpændə/',
          meaning: '熊猫',
          sentence: 'A panda.',
          image: 'english-animal-panda',
          audio: '/subpkg/english-animal/static/audio/panda.mp3',
          sentenceAudio: '/subpkg/english-animal/static/audio/panda-sentence.mp3',
        },
        {
          word: 'pig',
          phonetic: '/pɪɡ/',
          meaning: '猪',
          sentence: 'A pig.',
          image: 'english-animal-pig',
          audio: '/subpkg/english-animal/static/audio/pig.mp3',
          sentenceAudio: '/subpkg/english-animal/static/audio/pig-sentence.mp3',
        },
        {
          word: 'rabbit',
          phonetic: '/ˈræbɪt/',
          meaning: '兔子',
          sentence: 'A rabbit.',
          image: 'english-animal-rabbit',
          audio: '/subpkg/english-animal/static/audio/rabbit.mp3',
          sentenceAudio: '/subpkg/english-animal/static/audio/rabbit-sentence.mp3',
        },
        {
          word: 'tiger',
          phonetic: '/ˈtaɪɡər/',
          meaning: '老虎',
          sentence: 'A tiger.',
          image: 'english-animal-tiger',
          audio: '/subpkg/english-animal/static/audio/tiger.mp3',
          sentenceAudio: '/subpkg/english-animal/static/audio/tiger-sentence.mp3',
        },
      ],
    },
    {
      id: 'body',
      title: '身体',
      items: [
        {
          word: 'arm',
          phonetic: '/ɑrm/',
          meaning: '胳膊',
          sentence: 'My arm.',
          image: 'english-body-arm',
          audio: '/subpkg/english-body/static/audio/arm.mp3',
          sentenceAudio: '/subpkg/english-body/static/audio/arm-sentence.mp3',
        },
        {
          word: 'ear',
          phonetic: '/ɪr/',
          meaning: '耳朵',
          sentence: 'My ear.',
          image: 'english-body-ear',
          audio: '/subpkg/english-body/static/audio/ear.mp3',
          sentenceAudio: '/subpkg/english-body/static/audio/ear-sentence.mp3',
        },
        {
          word: 'eye',
          phonetic: '/aɪ/',
          meaning: '眼睛',
          sentence: 'My eye.',
          image: 'english-body-eye',
          audio: '/subpkg/english-body/static/audio/eye.mp3',
          sentenceAudio: '/subpkg/english-body/static/audio/eye-sentence.mp3',
        },
        {
          word: 'face',
          phonetic: '/feɪs/',
          meaning: '脸',
          sentence: 'My face.',
          image: 'english-body-face',
          audio: '/subpkg/english-body/static/audio/face.mp3',
          sentenceAudio: '/subpkg/english-body/static/audio/face-sentence.mp3',
        },
        {
          word: 'finger',
          phonetic: '/ˈfɪŋɡər/',
          meaning: '手指',
          sentence: 'My finger.',
          image: 'english-body-finger',
          audio: '/subpkg/english-body/static/audio/finger.mp3',
          sentenceAudio: '/subpkg/english-body/static/audio/finger-sentence.mp3',
        },
        {
          word: 'foot',
          phonetic: '/fʊt/',
          meaning: '脚',
          sentence: 'My foot.',
          image: 'english-body-foot',
          audio: '/subpkg/english-body/static/audio/foot.mp3',
          sentenceAudio: '/subpkg/english-body/static/audio/foot-sentence.mp3',
        },
        {
          word: 'hair',
          phonetic: '/her/',
          meaning: '头发',
          sentence: 'My hair.',
          image: 'english-body-hair',
          audio: '/subpkg/english-body/static/audio/hair.mp3',
          sentenceAudio: '/subpkg/english-body/static/audio/hair-sentence.mp3',
        },
        {
          word: 'hand',
          phonetic: '/hænd/',
          meaning: '手',
          sentence: 'My hand.',
          image: 'english-body-hand',
          audio: '/subpkg/english-body/static/audio/hand.mp3',
          sentenceAudio: '/subpkg/english-body/static/audio/hand-sentence.mp3',
        },
        {
          word: 'head',
          phonetic: '/hed/',
          meaning: '头',
          sentence: 'My head.',
          image: 'english-body-head',
          audio: '/subpkg/english-body/static/audio/head.mp3',
          sentenceAudio: '/subpkg/english-body/static/audio/head-sentence.mp3',
        },
        {
          word: 'leg',
          phonetic: '/leɡ/',
          meaning: '腿',
          sentence: 'My leg.',
          image: 'english-body-leg',
          audio: '/subpkg/english-body/static/audio/leg.mp3',
          sentenceAudio: '/subpkg/english-body/static/audio/leg-sentence.mp3',
        },
        {
          word: 'mouth',
          phonetic: '/maʊθ/',
          meaning: '嘴巴',
          sentence: 'My mouth.',
          image: 'english-body-mouth',
          audio: '/subpkg/english-body/static/audio/mouth.mp3',
          sentenceAudio: '/subpkg/english-body/static/audio/mouth-sentence.mp3',
        },
        {
          word: 'nose',
          phonetic: '/noʊz/',
          meaning: '鼻子',
          sentence: 'My nose.',
          image: 'english-body-nose',
          audio: '/subpkg/english-body/static/audio/nose.mp3',
          sentenceAudio: '/subpkg/english-body/static/audio/nose-sentence.mp3',
        },
      ],
    },
    {
      id: 'fruit',
      title: '水果',
      items: [
        {
          word: 'apple',
          phonetic: '/ˈæpl/',
          meaning: '苹果',
          sentence: 'An apple.',
          image: 'english-fruit-apple',
          audio: '/subpkg/english-fruit/static/audio/apple.mp3',
          sentenceAudio: '/subpkg/english-fruit/static/audio/apple-sentence.mp3',
        },
        {
          word: 'banana',
          phonetic: '/bəˈnænə/',
          meaning: '香蕉',
          sentence: 'A banana.',
          image: 'english-fruit-banana',
          audio: '/subpkg/english-fruit/static/audio/banana.mp3',
          sentenceAudio: '/subpkg/english-fruit/static/audio/banana-sentence.mp3',
        },
        {
          word: 'cherry',
          phonetic: '/ˈtʃeri/',
          meaning: '樱桃',
          sentence: 'A cherry.',
          image: 'english-fruit-cherry',
          audio: '/subpkg/english-fruit/static/audio/cherry.mp3',
          sentenceAudio: '/subpkg/english-fruit/static/audio/cherry-sentence.mp3',
        },
        {
          word: 'grape',
          phonetic: '/ɡreɪp/',
          meaning: '葡萄',
          sentence: 'A grape.',
          image: 'english-fruit-grape',
          audio: '/subpkg/english-fruit/static/audio/grape.mp3',
          sentenceAudio: '/subpkg/english-fruit/static/audio/grape-sentence.mp3',
        },
        {
          word: 'kiwi',
          phonetic: '/ˈkiːwiː/',
          meaning: '猕猴桃',
          sentence: 'A kiwi.',
          image: 'english-fruit-kiwi',
          audio: '/subpkg/english-fruit/static/audio/kiwi.mp3',
          sentenceAudio: '/subpkg/english-fruit/static/audio/kiwi-sentence.mp3',
        },
        {
          word: 'lemon',
          phonetic: '/ˈlemən/',
          meaning: '柠檬',
          sentence: 'A lemon.',
          image: 'english-fruit-lemon',
          audio: '/subpkg/english-fruit/static/audio/lemon.mp3',
          sentenceAudio: '/subpkg/english-fruit/static/audio/lemon-sentence.mp3',
        },
        {
          word: 'mango',
          phonetic: '/ˈmæŋɡoʊ/',
          meaning: '芒果',
          sentence: 'A mango.',
          image: 'english-fruit-mango',
          audio: '/subpkg/english-fruit/static/audio/mango.mp3',
          sentenceAudio: '/subpkg/english-fruit/static/audio/mango-sentence.mp3',
        },
        {
          word: 'orange',
          phonetic: '/ˈɔrɪndʒ/',
          meaning: '橙子',
          sentence: 'An orange.',
          image: 'english-fruit-orange',
          audio: '/subpkg/english-fruit/static/audio/orange.mp3',
          sentenceAudio: '/subpkg/english-fruit/static/audio/orange-sentence.mp3',
        },
        {
          word: 'peach',
          phonetic: '/piːtʃ/',
          meaning: '桃子',
          sentence: 'A peach.',
          image: 'english-fruit-peach',
          audio: '/subpkg/english-fruit/static/audio/peach.mp3',
          sentenceAudio: '/subpkg/english-fruit/static/audio/peach-sentence.mp3',
        },
        {
          word: 'pear',
          phonetic: '/per/',
          meaning: '梨',
          sentence: 'A pear.',
          image: 'english-fruit-pear',
          audio: '/subpkg/english-fruit/static/audio/pear.mp3',
          sentenceAudio: '/subpkg/english-fruit/static/audio/pear-sentence.mp3',
        },
        {
          word: 'strawberry',
          phonetic: '/ˈstrɔberi/',
          meaning: '草莓',
          sentence: 'A strawberry.',
          image: 'english-fruit-strawberry',
          audio: '/subpkg/english-fruit/static/audio/strawberry.mp3',
          sentenceAudio: '/subpkg/english-fruit/static/audio/strawberry-sentence.mp3',
        },
        {
          word: 'watermelon',
          phonetic: '/ˈwɔtərmelən/',
          meaning: '西瓜',
          sentence: 'A watermelon.',
          image: 'english-fruit-watermelon',
          audio: '/subpkg/english-fruit/static/audio/watermelon.mp3',
          sentenceAudio: '/subpkg/english-fruit/static/audio/watermelon-sentence.mp3',
        },
      ],
    },
    {
      id: 'food',
      title: '食物',
      items: [
        {
          word: 'bread',
          phonetic: '/bred/',
          meaning: '面包',
          sentence: 'Some bread.',
          image: 'english-food-bread',
          audio: '/subpkg/english-food/static/audio/bread.mp3',
          sentenceAudio: '/subpkg/english-food/static/audio/bread-sentence.mp3',
        },
        {
          word: 'cake',
          phonetic: '/keɪk/',
          meaning: '蛋糕',
          sentence: 'A cake.',
          image: 'english-food-cake',
          audio: '/subpkg/english-food/static/audio/cake.mp3',
          sentenceAudio: '/subpkg/english-food/static/audio/cake-sentence.mp3',
        },
        {
          word: 'candy',
          phonetic: '/ˈkændi/',
          meaning: '糖果',
          sentence: 'A candy.',
          image: 'english-food-candy',
          audio: '/subpkg/english-food/static/audio/candy.mp3',
          sentenceAudio: '/subpkg/english-food/static/audio/candy-sentence.mp3',
        },
        {
          word: 'cookie',
          phonetic: '/ˈkʊki/',
          meaning: '饼干',
          sentence: 'A cookie.',
          image: 'english-food-cookie',
          audio: '/subpkg/english-food/static/audio/cookie.mp3',
          sentenceAudio: '/subpkg/english-food/static/audio/cookie-sentence.mp3',
        },
        {
          word: 'egg',
          phonetic: '/eɡ/',
          meaning: '鸡蛋',
          sentence: 'An egg.',
          image: 'english-food-egg',
          audio: '/subpkg/english-food/static/audio/egg.mp3',
          sentenceAudio: '/subpkg/english-food/static/audio/egg-sentence.mp3',
        },
        {
          word: 'juice',
          phonetic: '/dʒuːs/',
          meaning: '果汁',
          sentence: 'Some juice.',
          image: 'english-food-juice',
          audio: '/subpkg/english-food/static/audio/juice.mp3',
          sentenceAudio: '/subpkg/english-food/static/audio/juice-sentence.mp3',
        },
        {
          word: 'meat',
          phonetic: '/miːt/',
          meaning: '肉',
          sentence: 'Some meat.',
          image: 'english-food-meat',
          audio: '/subpkg/english-food/static/audio/meat.mp3',
          sentenceAudio: '/subpkg/english-food/static/audio/meat-sentence.mp3',
        },
        {
          word: 'milk',
          phonetic: '/mɪlk/',
          meaning: '牛奶',
          sentence: 'Some milk.',
          image: 'english-food-milk',
          audio: '/subpkg/english-food/static/audio/milk.mp3',
          sentenceAudio: '/subpkg/english-food/static/audio/milk-sentence.mp3',
        },
        {
          word: 'noodles',
          phonetic: '/ˈnuːdlz/',
          meaning: '面条',
          sentence: 'Some noodles.',
          image: 'english-food-noodles',
          audio: '/subpkg/english-food/static/audio/noodles.mp3',
          sentenceAudio: '/subpkg/english-food/static/audio/noodles-sentence.mp3',
        },
        {
          word: 'pizza',
          phonetic: '/ˈpitsə/',
          meaning: '披萨',
          sentence: 'A pizza.',
          image: 'english-food-pizza',
          audio: '/subpkg/english-food/static/audio/pizza.mp3',
          sentenceAudio: '/subpkg/english-food/static/audio/pizza-sentence.mp3',
        },
        {
          word: 'rice',
          phonetic: '/raɪs/',
          meaning: '米饭',
          sentence: 'Some rice.',
          image: 'english-food-rice',
          audio: '/subpkg/english-food/static/audio/rice.mp3',
          sentenceAudio: '/subpkg/english-food/static/audio/rice-sentence.mp3',
        },
        {
          word: 'tea',
          phonetic: '/tiː/',
          meaning: '茶',
          sentence: 'I like tea.',
          image: 'english-food-tea',
          audio: '/subpkg/english-food/static/audio/tea.mp3',
          sentenceAudio: '/subpkg/english-food/static/audio/tea-sentence.mp3',
        },
      ],
    },
    {
      id: 'nature',
      title: '自然',
      items: [
        {
          word: 'cloud',
          phonetic: '/klaʊd/',
          meaning: '云',
          sentence: 'A cloud.',
          image: 'english-nature-cloud',
          audio: '/subpkg/english-nature/static/audio/cloud.mp3',
          sentenceAudio: '/subpkg/english-nature/static/audio/cloud-sentence.mp3',
        },
        {
          word: 'flower',
          phonetic: '/ˈflaʊər/',
          meaning: '花',
          sentence: 'A flower.',
          image: 'english-nature-flower',
          audio: '/subpkg/english-nature/static/audio/flower.mp3',
          sentenceAudio: '/subpkg/english-nature/static/audio/flower-sentence.mp3',
        },
        {
          word: 'grass',
          phonetic: '/ɡræs/',
          meaning: '草',
          sentence: 'The grass.',
          image: 'english-nature-grass',
          audio: '/subpkg/english-nature/static/audio/grass.mp3',
          sentenceAudio: '/subpkg/english-nature/static/audio/grass-sentence.mp3',
        },
        {
          word: 'leaf',
          phonetic: '/liːf/',
          meaning: '叶子',
          sentence: 'A leaf.',
          image: 'english-nature-leaf',
          audio: '/subpkg/english-nature/static/audio/leaf.mp3',
          sentenceAudio: '/subpkg/english-nature/static/audio/leaf-sentence.mp3',
        },
        {
          word: 'moon',
          phonetic: '/muːn/',
          meaning: '月亮',
          sentence: 'The moon.',
          image: 'english-nature-moon',
          audio: '/subpkg/english-nature/static/audio/moon.mp3',
          sentenceAudio: '/subpkg/english-nature/static/audio/moon-sentence.mp3',
        },
        {
          word: 'rain',
          phonetic: '/reɪn/',
          meaning: '雨',
          sentence: 'The rain.',
          image: 'english-nature-rain',
          audio: '/subpkg/english-nature/static/audio/rain.mp3',
          sentenceAudio: '/subpkg/english-nature/static/audio/rain-sentence.mp3',
        },
        {
          word: 'river',
          phonetic: '/ˈrɪvər/',
          meaning: '河',
          sentence: 'A river.',
          image: 'english-nature-river',
          audio: '/subpkg/english-nature/static/audio/river.mp3',
          sentenceAudio: '/subpkg/english-nature/static/audio/river-sentence.mp3',
        },
        {
          word: 'snow',
          phonetic: '/snoʊ/',
          meaning: '雪',
          sentence: 'The snow.',
          image: 'english-nature-snow',
          audio: '/subpkg/english-nature/static/audio/snow.mp3',
          sentenceAudio: '/subpkg/english-nature/static/audio/snow-sentence.mp3',
        },
        {
          word: 'star',
          phonetic: '/stɑr/',
          meaning: '星星',
          sentence: 'A star.',
          image: 'english-nature-star',
          audio: '/subpkg/english-nature/static/audio/star.mp3',
          sentenceAudio: '/subpkg/english-nature/static/audio/star-sentence.mp3',
        },
        {
          word: 'sun',
          phonetic: '/sʌn/',
          meaning: '太阳',
          sentence: 'The sun.',
          image: 'english-nature-sun',
          audio: '/subpkg/english-nature/static/audio/sun.mp3',
          sentenceAudio: '/subpkg/english-nature/static/audio/sun-sentence.mp3',
        },
        {
          word: 'tree',
          phonetic: '/triː/',
          meaning: '树',
          sentence: 'A tree.',
          image: 'english-nature-tree',
          audio: '/subpkg/english-nature/static/audio/tree.mp3',
          sentenceAudio: '/subpkg/english-nature/static/audio/tree-sentence.mp3',
        },
        {
          word: 'wind',
          phonetic: '/wɪnd/',
          meaning: '风',
          sentence: 'The wind.',
          image: 'english-nature-wind',
          audio: '/subpkg/english-nature/static/audio/wind.mp3',
          sentenceAudio: '/subpkg/english-nature/static/audio/wind-sentence.mp3',
        },
      ],
    },
    {
      id: 'transport',
      title: '交通',
      items: [
        {
          word: 'bike',
          phonetic: '/baɪk/',
          meaning: '自行车',
          sentence: 'I see a bike.',
          image: 'english-transport-bike',
          audio: '/subpkg/english-transport/static/audio/bike.mp3',
          sentenceAudio: '/subpkg/english-transport/static/audio/bike-sentence.mp3',
        },
        {
          word: 'boat',
          phonetic: '/boʊt/',
          meaning: '船',
          sentence: 'I see a boat.',
          image: 'english-transport-boat',
          audio: '/subpkg/english-transport/static/audio/boat.mp3',
          sentenceAudio: '/subpkg/english-transport/static/audio/boat-sentence.mp3',
        },
        {
          word: 'bus',
          phonetic: '/bʌs/',
          meaning: '公交车',
          sentence: 'I see a bus.',
          image: 'english-transport-bus',
          audio: '/subpkg/english-transport/static/audio/bus.mp3',
          sentenceAudio: '/subpkg/english-transport/static/audio/bus-sentence.mp3',
        },
        {
          word: 'car',
          phonetic: '/kɑr/',
          meaning: '汽车',
          sentence: 'I see a car.',
          image: 'english-transport-car',
          audio: '/subpkg/english-transport/static/audio/car.mp3',
          sentenceAudio: '/subpkg/english-transport/static/audio/car-sentence.mp3',
        },
        {
          word: 'plane',
          phonetic: '/pleɪn/',
          meaning: '飞机',
          sentence: 'I see a plane.',
          image: 'english-transport-plane',
          audio: '/subpkg/english-transport/static/audio/plane.mp3',
          sentenceAudio: '/subpkg/english-transport/static/audio/plane-sentence.mp3',
        },
        {
          word: 'rocket',
          phonetic: '/ˈrɑkɪt/',
          meaning: '火箭',
          sentence: 'I see a rocket.',
          image: 'english-transport-rocket',
          audio: '/subpkg/english-transport/static/audio/rocket.mp3',
          sentenceAudio: '/subpkg/english-transport/static/audio/rocket-sentence.mp3',
        },
        {
          word: 'ship',
          phonetic: '/ʃɪp/',
          meaning: '大船',
          sentence: 'I see a ship.',
          image: 'english-transport-ship',
          audio: '/subpkg/english-transport/static/audio/ship.mp3',
          sentenceAudio: '/subpkg/english-transport/static/audio/ship-sentence.mp3',
        },
        {
          word: 'subway',
          phonetic: '/ˈsʌbweɪ/',
          meaning: '地铁',
          sentence: 'I see a subway.',
          image: 'english-transport-subway',
          audio: '/subpkg/english-transport/static/audio/subway.mp3',
          sentenceAudio: '/subpkg/english-transport/static/audio/subway-sentence.mp3',
        },
        {
          word: 'taxi',
          phonetic: '/ˈtæksi/',
          meaning: '出租车',
          sentence: 'I see a taxi.',
          image: 'english-transport-taxi',
          audio: '/subpkg/english-transport/static/audio/taxi.mp3',
          sentenceAudio: '/subpkg/english-transport/static/audio/taxi-sentence.mp3',
        },
        {
          word: 'train',
          phonetic: '/treɪn/',
          meaning: '火车',
          sentence: 'I see a train.',
          image: 'english-transport-train',
          audio: '/subpkg/english-transport/static/audio/train.mp3',
          sentenceAudio: '/subpkg/english-transport/static/audio/train-sentence.mp3',
        },
        {
          word: 'truck',
          phonetic: '/trʌk/',
          meaning: '卡车',
          sentence: 'I see a truck.',
          image: 'english-transport-truck',
          audio: '/subpkg/english-transport/static/audio/truck.mp3',
          sentenceAudio: '/subpkg/english-transport/static/audio/truck-sentence.mp3',
        },
        {
          word: 'van',
          phonetic: '/væn/',
          meaning: '面包车',
          sentence: 'I see a van.',
          image: 'english-transport-van',
          audio: '/subpkg/english-transport/static/audio/van.mp3',
          sentenceAudio: '/subpkg/english-transport/static/audio/van-sentence.mp3',
        },
      ],
    },
  ],
}
