module.exports = {
  categories: [
    {
      id: 'transport',
      title: '交通',
      items: [
        {
          word: 'bike',
          phonetic: '/baɪk/',
          meaning: '自行车',
          sentence: 'I see a bike.',
          image: 'english-transport-bike',
          audio: '/subpkg/english-transport/static/audio/bike.mp3',
          sentenceAudio: '/subpkg/english-transport/static/audio/bike-sentence.mp3',
        },
        {
          word: 'boat',
          phonetic: '/boʊt/',
          meaning: '船',
          sentence: 'I see a boat.',
          image: 'english-transport-boat',
          audio: '/subpkg/english-transport/static/audio/boat.mp3',
          sentenceAudio: '/subpkg/english-transport/static/audio/boat-sentence.mp3',
        },
        {
          word: 'bus',
          phonetic: '/bʌs/',
          meaning: '公交车',
          sentence: 'I see a bus.',
          image: 'english-transport-bus',
          audio: '/subpkg/english-transport/static/audio/bus.mp3',
          sentenceAudio: '/subpkg/english-transport/static/audio/bus-sentence.mp3',
        },
        {
          word: 'car',
          phonetic: '/kɑr/',
          meaning: '汽车',
          sentence: 'I see a car.',
          image: 'english-transport-car',
          audio: '/subpkg/english-transport/static/audio/car.mp3',
          sentenceAudio: '/subpkg/english-transport/static/audio/car-sentence.mp3',
        },
        {
          word: 'plane',
          phonetic: '/pleɪn/',
          meaning: '飞机',
          sentence: 'I see a plane.',
          image: 'english-transport-plane',
          audio: '/subpkg/english-transport/static/audio/plane.mp3',
          sentenceAudio: '/subpkg/english-transport/static/audio/plane-sentence.mp3',
        },
        {
          word: 'rocket',
          phonetic: '/ˈrɑkɪt/',
          meaning: '火箭',
          sentence: 'I see a rocket.',
          image: 'english-transport-rocket',
          audio: '/subpkg/english-transport/static/audio/rocket.mp3',
          sentenceAudio: '/subpkg/english-transport/static/audio/rocket-sentence.mp3',
        },
        {
          word: 'ship',
          phonetic: '/ʃɪp/',
          meaning: '大船',
          sentence: 'I see a ship.',
          image: 'english-transport-ship',
          audio: '/subpkg/english-transport/static/audio/ship.mp3',
          sentenceAudio: '/subpkg/english-transport/static/audio/ship-sentence.mp3',
        },
        {
          word: 'subway',
          phonetic: '/ˈsʌbweɪ/',
          meaning: '地铁',
          sentence: 'I see a subway.',
          image: 'english-transport-subway',
          audio: '/subpkg/english-transport/static/audio/subway.mp3',
          sentenceAudio: '/subpkg/english-transport/static/audio/subway-sentence.mp3',
        },
        {
          word: 'taxi',
          phonetic: '/ˈtæksi/',
          meaning: '出租车',
          sentence: 'I see a taxi.',
          image: 'english-transport-taxi',
          audio: '/subpkg/english-transport/static/audio/taxi.mp3',
          sentenceAudio: '/subpkg/english-transport/static/audio/taxi-sentence.mp3',
        },
        {
          word: 'train',
          phonetic: '/treɪn/',
          meaning: '火车',
          sentence: 'I see a train.',
          image: 'english-transport-train',
          audio: '/subpkg/english-transport/static/audio/train.mp3',
          sentenceAudio: '/subpkg/english-transport/static/audio/train-sentence.mp3',
        },
        {
          word: 'truck',
          phonetic: '/trʌk/',
          meaning: '卡车',
          sentence: 'I see a truck.',
          image: 'english-transport-truck',
          audio: '/subpkg/english-transport/static/audio/truck.mp3',
          sentenceAudio: '/subpkg/english-transport/static/audio/truck-sentence.mp3',
        },
        {
          word: 'van',
          phonetic: '/væn/',
          meaning: '面包车',
          sentence: 'I see a van.',
          image: 'english-transport-van',
          audio: '/subpkg/english-transport/static/audio/van.mp3',
          sentenceAudio: '/subpkg/english-transport/static/audio/van-sentence.mp3',
        },
      ],
    },
  ],
}
